#!/usr/bin/perl
use strict;
use warnings;
use App::Rangeops;

App::Rangeops->run;

=head1 OVERVIEW

For help with App::Rangeops, run "rangeops help"

=cut

__END__

perl -I lib/ script/rangeops

perl -I lib/ script/rangeops sort t/II.links.tsv -o stdout
cat t/II.links.tsv \
    | perl -I lib/ script/rangeops sort stdin -o t/II.sort.tsv

perl -I lib/ script/rangeops merge t/II.links.tsv -o stdout
cat t/II.links.tsv \
    | perl -I lib/ script/rangeops merge stdin -o t/II.merge.tsv

perl -I lib/ script/rangeops clean t/II.sort.tsv -o stdout
perl -I lib/ script/rangeops clean t/II.sort.tsv -r t/II.merge.tsv -o stdout
cat t/II.sort.tsv \
    | perl -I lib/ script/rangeops clean stdin -r t/II.merge.tsv -o t/II.clean.tsv

perl -I lib/ script/rangeops connect t/II.clean.tsv -v -o stdout

# S288c chr II
perl -I lib/ script/rangeops merge t/II.lastz.tsv t/II.blast.tsv -o stdout \
    > t/II.merge.tsv

perl -I lib/ script/rangeops sort t/II.lastz.tsv t/II.blast.tsv -o stdout \
    | perl -I lib/ script/rangeops clean stdin -r t/II.merge.tsv -o stdout \
    > t/II.clean.tsv

# S288c
perl -I lib/ script/rangeops merge S288c/links.lastz.tsv S288c/links.blast.tsv \
    -o S288c/merge.tsv

perl -I lib/ script/rangeops sort S288c/links.lastz.tsv S288c/links.blast.tsv \
    -o S288c/sort.tsv

perl -I lib/ script/rangeops clean S288c/sort.tsv -o S288c/clean.tsv

perl -I lib/ script/rangeops connect S288c/clean.tsv -o S288c/connect.tsv

wc -l S288c/*.tsv

     351 S288c/clean.tsv
     155 S288c/connect.tsv
     566 S288c/links.blast.tsv
     346 S288c/links.lastz.tsv
     132 S288c/merge.tsv
     626 S288c/sort.tsv
