#!/usr/bin/perl
use App::Rangeops;

App::Rangeops->run;

=head1 OVERVIEW

For help with App::Rangeops, run "rangeops help"

=cut

__END__

perl -I lib/ script/rangeops

perl -I lib/ script/rangeops merge t/I.links.tsv -o stdout
