#!/usr/bin/perl
use strict;
use warnings;
use App::Rangeops;

App::Rangeops->run;

=head1 OVERVIEW

For help with App::Rangeops, run "rangeops help"

=cut

__END__

perl -I lib/ script/rangeops

perl -I lib/ script/rangeops sort t/II.links.tsv -o stdout
cat t/II.links.tsv \
    | perl -I lib/ script/rangeops sort stdin -o t/II.sort.tsv

perl -I lib/ script/rangeops merge t/II.links.tsv -o stdout
cat t/II.links.tsv \
    | perl -I lib/ script/rangeops merge stdin -o t/II.merge.tsv

perl -I lib/ script/rangeops clean t/II.sort.tsv -o stdout
perl -I lib/ script/rangeops clean t/II.sort.tsv -r t/II.merge.tsv -o stdout
cat t/II.sort.tsv \
    | perl -I lib/ script/rangeops clean stdin -r t/II.merge.tsv -o t/II.clean.tsv

perl -I lib/ script/rangeops connect t/II.clean.tsv -v -o t/II.connect.tsv

perl -I lib/ script/rangeops filter t/II.connect.tsv -n 2 -o stdout

perl -I lib/ script/rangeops circos t/II.connect.tsv -o stdout
perl -I lib/ script/rangeops circos t/II.connect.tsv -l -o stdout

cat ~/data/alignment/Ensembl/S288c/I.fa > xt/genome.fa
samtools faidx xt/genome.fa
perl -I lib/ script/rangeops create xt/I.connect.tsv -g xt/genome.fa -o stdout

# S288c chr II
perl -I lib/ script/rangeops merge t/II.lastz.tsv t/II.blast.tsv -o stdout \
    > t/II.merge.tsv

perl -I lib/ script/rangeops sort t/II.lastz.tsv t/II.blast.tsv -o stdout \
    | perl -I lib/ script/rangeops clean stdin -r t/II.merge.tsv -o stdout \
    > t/II.clean.tsv

# S288c
perl -I lib/ script/rangeops merge S288c/links.lastz.tsv S288c/links.blast.tsv \
    -o S288c/merge.tsv

perl -I lib/ script/rangeops sort S288c/links.lastz.tsv S288c/links.blast.tsv \
    -o S288c/sort.tsv

perl -I lib/ script/rangeops clean S288c/sort.tsv -r S288c/merge.tsv \
    -o S288c/clean.tsv

perl -I lib/ script/rangeops connect S288c/clean.tsv -o S288c/connect.tsv

wc -l S288c/*.tsv

     275 S288c/clean.tsv
     155 S288c/connect.tsv
     566 S288c/links.blast.tsv
     346 S288c/links.lastz.tsv
     132 S288c/merge.tsv
     626 S288c/sort.tsv

cat S288c/connect.tsv \
    | perl -nla -F"\t" -e 'print for @F' \
    | runlist cover stdin -o S288c/cover.yml

runlist stat --size S288c/chr.sizes S288c/cover.yml -o stdout
perl ~/Scripts/egas/cover_figure.pl --size t/chr.sizes -f S288c/cover.yml

# Atha
perl -I lib/ script/rangeops merge Atha/links.lastz.tsv Atha/links.blast.tsv \
    -o Atha/merge.tsv -p 5

perl -I lib/ script/rangeops sort Atha/links.lastz.tsv Atha/links.blast.tsv \
    -o Atha/sort.tsv

perl -I lib/ script/rangeops clean Atha/sort.tsv -r Atha/merge.tsv \
    -o Atha/clean.tsv

perl -I lib/ script/rangeops connect Atha/clean.tsv -o Atha/connect.tsv

wc -l Atha/*.tsv

cat Atha/connect.tsv \
    | perl -nla -F"\t" -e 'print for @F' \
    | runlist cover stdin -o Atha/cover.yml

runlist stat --size Atha/chr.sizes Atha/cover.yml -o stdout